language: node_js
services: mongodb
node_js:
- '12'
install:
- cd backend ; npm install
script:
- cd ..
- cd backend ; npm test
- echo $SERVER_PRIVATE_KEY > privatekey
- chmod 600 privatekey
- ssh -i privatekey payitforward@68.183.120.255
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 68.183.120.255
