language: node_js
servers: mongodb
node_js:
- '12'
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: test
      name: "Backend Test"
      install:
        - cd backend 
        - npm install
      script:
        - npm test
    -
      name: "Frontend Test"
      install:
        - cd frontend
        - npm install
      script:
        - npm test
    - stage: deploy
      before_script:
        - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
      script:
        - deploy.sh

stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = master
      
